import { StyleSheet } from "react-native";
import { textColor, black, primary, header } from "../../styles/global";

export default StyleSheet.create({
  container: {
    flex: 1,
    // justifyContent: "flex-start",
    // alignItems: "flex-start",
    paddingTop: 5,
    paddingBottom: 15,
    paddingHorizontal: 5,
  },
  container2: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 5,
    paddingLeft: 20,
  },
  title: {
    fontSize: 20,
    fontFamily: "Avenire-Regular",
    color: textColor,
    paddingLeft: 15,
    paddingVertical: 10,
  },
  titleEmpty: {
    fontSize: 17,
    fontFamily: "Avenire-Regular",
    color: textColor,
    textAlign: "center",
    paddingBottom: 30,
    paddingHorizontal: 8,
  },
  containerCard: {
    height: 160,
    width: 120,
    backgroundColor: primary,
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    borderRadius: 10,
    marginVertical: 10,
    marginRight: 20,
    marginLeft: 5,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  containerCardProducts: {
    height: 160,
    width: "42%",
    minWidth: 130,
    backgroundColor: primary,
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    borderRadius: 10,
    marginVertical: 10,
    marginRight: 20,
    marginLeft: 5,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  containerCardMarket: {
    height: 140,
    width: 120,
    backgroundColor: primary,
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    borderRadius: 10,
    marginVertical: 10,
    marginRight: 20,
    marginLeft: 5,
  },
  containerCardMarketScreen: {
    height: 140,
    width: "42%",
    minWidth: 130,
    backgroundColor: primary,
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    borderRadius: 10,
    marginVertical: 10,
    marginRight: 20,
    marginLeft: 5,
  },
  cardContiner: {
    height: 60,
    width: "100%",
    backgroundColor: "transparent",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  cardImg: {
    position: "absolute",
    right: 10,
    top: 10,
    zIndex: 1,
  },
  nameContainer: {
    padding: 8,
  },
  name: {
    fontSize: 12,
    fontFamily: "Roboto-Regular",
    paddingBottom: 8,
  },
  list: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 5,
  },
  subName: {
    fontSize: 10,
    fontFamily: "Roboto-Regular",
    paddingLeft: 8,
  },
});
