import { StyleSheet } from "react-native";
import {
  textColor,
  backgroundColor,
  primary,
  black,
  buttonColor,
  grayColor,
} from "../../styles/global";
export default StyleSheet.create({
  container: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: backgroundColor,
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  title: {
    fontSize: 20,
    color: textColor,
    paddingTop: 23,
    paddingBottom: 10,
    fontFamily: "Avenire-Regular",
  },
  market: {
    display: "flex",
    flexDirection: "row",
    alignSelf: "flex-start",
    alignItems: "center",
    backgroundColor: primary,
    padding: 15,
    borderRadius: 17,
    width: "100%",
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  marketName: {
    fontSize: 16,
    color: buttonColor,
    letterSpacing: 1,
  },
  productsList: {
    backgroundColor: primary,
    width: "100%",
    borderRadius: 17,
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  productsTitle: {
    fontSize: 16,
    color: black,
    padding: 15,
    fontFamily: "Roboto-Regular",
  },
  changeProducts: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderBottomColor: grayColor,
    borderBottomWidth: 0.5,
    width: "100%",
  },
  image: {
    width: 15,
    height: 15,
  },
  itemsContainer: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderBottomColor: grayColor,
    borderBottomWidth: 0.5,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 30,
  },
  itemName: {
    fontSize: 14,
    fontFamily: "Roboto-Regular",
    color: textColor,
  },
  item: {
    fontSize: 13,
    fontFamily: "Roboto-Regular",
  },
  itemContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  number: {
    textAlign: "center",
  },
  noteContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 30,
  },
  textInput: {
    backgroundColor: primary,
    width: "100%",
    height: 150,
    textAlignVertical: "top",
    paddingLeft: 15,
    paddingTop: 15,
    fontSize: 16,
    borderRadius: 17,
    marginBottom: 20,
    shadowColor: black,
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  locationContainer: {
    width: "100%",
    height: 250,
    marginBottom: 30,
  },
  konfirmoContainer: {
    width: "100%",
    alignItems: "center",
  },
  deleteBox: {
    backgroundColor: buttonColor,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 15,
    borderRadius: 10,
    fontFamily: "Avenire-Regular",
    minHeight: 30,
  },
  cartContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  cart: {
    justifyContent: "center",
    alignItems: "center",
  },
  emptyCart: {
    height: 120,
    width: 120,
  },
  cartButton: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  containerCard: {
    width: "90%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 15,
  },
  containerInfo: {
    display: "flex",
    flexDirection: "row",
  },
  cardImg: {
    height: 50,
    width: 50,
    resizeMode: "cover",
  },
  nameContainer: {
    paddingLeft: 15,
  },
  name: {
    fontSize: 16,
    fontFamily: "Avenire-Regular",
    color: textColor,
  },
  price: {
    fontSize: 14,
    fontFamily: "Avenire-Regular",
    color: black,
  },
  // flatlist: {
  //   width: "90%",
  //   justifyContent: "center",
  // },
  porosia: {
    justifyContent: "center",
    alignItems: "center",
  },
  porosiaText: {
    fontSize: 17,
    fontFamily: "Avenire-Regular",
  },
});
