import { StyleSheet } from "react-native";
import {
  textColor,
  primary,
  grayColor,
  buttonColor,
} from "../../styles/global";

export default StyleSheet.create({
  topContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
  },
  image: {
    width: 100,
    height: 100,
    borderRadius: 100,
  },
  bottomContainer: {
    alignSelf: "center",
    width: "95%",
    borderRadius: 20,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginTop: 10,
    paddingHorizontal: 30,
    paddingVertical: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 2,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
    backgroundColor: primary,
  },
  list: {
    width: "100%",
    paddingVertical: 5,
  },
  description: {
    fontSize: 15,
    color: textColor,
    fontFamily: "Roboto-Regular",
    paddingBottom: 5,
    paddingTop: 5,
  },
  footer: {
    alignItems: "center",
    marginTop: 40,
    width: "100%",
  },
  locationContainer: {
    marginTop: 10,
    padding: 15,
    backgroundColor: primary,
    borderRadius: 17,
    width: "99%",
    shadowColor: "black",
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 10,
    marginLeft: 1,
  },
  friendsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // borderBottomColor: grayColor,
    // borderBottomWidth: 0.5,
  },
  itemsContainerLocation: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  title: {
    fontSize: 18,
    fontFamily: "Roboto-Regular",
    color: "black",
  },
  subTitle: {
    fontSize: 16,
    fontFamily: "Roboto-Regular",
    color: buttonColor,
  },
  default: {
    paddingLeft: 5,
    color: "#5c5c5c",
    fontFamily: "Roboto-Regular",
  },
  adressesContainer: {
    paddingVertical: 5,
    borderBottomColor: grayColor,
    borderBottomWidth: 0.5,
    flex: 1,
    width: "100%",
    // height: 300,
  },
  adressesName: {
    fontSize: 16,
    color: "black",
    fontFamily: "Roboto-Regular",
  },
  descriptionName: {
    fontSize: 14,
    color: textColor,
    fontFamily: "Avenire-Regular",
    paddingBottom: 5,
  },
  title: {
    fontSize: 17,
    color: textColor,
    paddingTop: 23,
    paddingBottom: 10,
    // fontFamily: "Avenire-Regular",
  },
  logout: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 10,
  },
  productsList: {
    backgroundColor: primary,
    width: "100%",
    borderRadius: 17,
    shadowColor: "black",
    shadowOffset: {
      width: 5,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  productsTitle: {
    fontSize: 16,
    color: "black",
    padding: 15,
    fontFamily: "Roboto-Regular",
  },
  itemsContainer: {
    paddingLeft: 15,
    paddingVertical: 8,
    borderBottomColor: grayColor,
    borderBottomWidth: 0.5,
  },
  item: {
    fontSize: 14,
    fontFamily: "Roboto-Regular",
  },

 
  deleteBox: {
    backgroundColor: buttonColor,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 50,
    maxHeight: 100,
    paddingHorizontal: 15,
    borderRadius: 10,
    fontFamily: "Avenire-Bold",
    marginTop: 10,
  },
  scrollView: {
    flexGrow: 1,
    marginTop: 50,
    alignItems: "center",
    paddingBottom: 60,
  },
  marketContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 30,
    paddingVertical: 10,
  },
});
